### ISSUE TITLE
Support a textual representation of word definition

### ISSUE THREAD

**Issue by na4zagin3** [na4zagin3/hermeneus#3]
We need a textual representation of word definition for compatibility with gettext ecosystem.

### Idea
```
  - word: "助数詞" # 数値に関する
    context: "com.example.shopping.buy"
    agreement:
      counter: satsu
    translation:
      - condition:
          counter: dai
        translation: "台"
      - condition:
          counter: satsu
        translation: "冊"
```
will be
```
{@(counter=satsu)counter=dai~台;counter=satsu~translation~冊}
```
or something
